active: custom
apis:
  custom:
    api_key: sk-FcsCdLZnWi5jrvIt7jwCzjyGtqxN70vJsaQIAprx1rGFgWVi
    base_url: https://us.novaiapi.com/v1
    max_tokens: 4096
    model: '[次]gemini-3.1-pro-preview-thinking'
    name: 自定义 API
    temperature: 0.7
  gemini:
    api_key: sk-FcsCdLZnWi5jrvIt7jwCzjyGtqxN70vJsaQIAprx1rGFgWVi
    base_url: https://us.novaiapi.com/v1
    max_tokens: 4096
    model: '[次]gemini-3.1-pro-preview-thinking'
    name: Google Gemini
    temperature: 0.7
    use_native_sdk: false
